name: Update GitHub Pages

on:
  push:
    tags:
      - '**'

jobs:
  pages:
    name: Update GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code from release
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          path: release
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: pages
          ref: gh-pages
      - name: Update gh-pages branch with latest docs
        run: |
          cd "$GITHUB_WORKSPACE/pages"
          cp "$GITHUB_WORKSPACE/release/README.md" ./index.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "docs: update docs for ${{ github.ref_name }}"
          git push
